### PR TITLE
Kill HttpError

### LINKED ISSUE #338: Cleanup the rust error handling in the server - less and cleaner types
Cleanup the error handling in both raft (where the modules apply stuff to disk) and HTTP layer.
- Significantly reduce the amount of error types in coyote_error::Error
- Remove the notion of HttpError and instead have specific types (but all should have code + description like http error has). We don't care about HTTP types anymore.
- Raft requires serializable errors, so let's see if we can have something instead of HttpError which is "operational error" or whatever we want to call it, that has a few simple types, and is serializable for raft. E.g: not_found (for entity not found), bad_request (when a user makes an error), internal_error (when we want to expose the error to customer, but it's a 500 essentially), and that's it for now? Document them well to explain what they should be used for, and let's just use them?
    - Can potentially add a conflict, though I feel like that is just a confusing subset of bad_request?
    - Or maybe can split bad_request to two, one is a sort of validation/code did something wrong, and another is operational (e.g. a conflict, or some runtime case) - so essentially differentiate between permanent bad request and situational/context based.

Related to #302, as it enables us to have a small set of error types that people can `catch`.

### PR DESCRIPTION
**Pull request by svix-jplatte**
Closes https://github.com/svix/coyote-private/issues/338.

Best reviewed commit by commit.

### CODE REVIEW

File: crates/coyote-error/src/lib.rs [hunk 1]
```diff
@@ -147,9 +139,14 @@ impl<T> Traceable<T> for Result<T> {
 #[derive(Debug)]
 pub enum ErrorType {
     /// A generic error
-    Generic(String),
-    /// Any kind of HttpError
-    Http(HttpError),
+    Generic {
```
Comment (svix-gabriel) [inline crates/coyote-error/src/lib.rs:142]: Selfishly, I wonder if we should rename this from `Generic` to `Internal`.

File: crates/coyote-error/src/lib.rs [hunk 2]
```diff
@@ -147,9 +139,14 @@ impl<T> Traceable<T> for Result<T> {
...
+        message: String,
+        trace: Vec<&'static Location<'static>>,
+    },
+    /// Bad user input
+    BadRequest(StandardErrorBody),
+    /// Entity not found
```
Comment (svix-gabriel) [inline crates/coyote-error/src/lib.rs:148]:
```suggestion
    BadRequest(StandardErrorBody),
```

Nits, but I think the enums here are self documenting enough that we don't really need these comments (I realize a lot of these comments were here before, but since we're refactoring things anyway....)

**Review by svix-gabriel — APPROVED** [review]

**Comment by svix-gabriel** [comment]
My feedback is non blocking. Feel free to resolve the comments if you disagree or want to address them in a separate PR
